'use client';
import {useEffect,useState, type FormEvent} from 'react';
import {inicial,STORAGE_KEY} from '../demo';
import type {Datos,Estado,Audiencia} from '../types';
import {categorias,normalizarRadicado,sugerirCategoria,coincidenciasRadicado} from '../archivo';
import {datosSchema} from '../lib/datos';
const tabs=['Inicio','Expedientes','Archivo documental','Plantillas','Agenda','Dispositivos'] as const;
const campo=(f:FormData,k:string)=>String(f.get(k)||'').trim();
export default function Home(){
 const [datos,setDatos]=useState<Datos>(inicial),[listo,setListo]=useState(false),[aviso,setAviso]=useState(''),[tab,setTab]=useState<string>('Inicio'),[busqueda,setBusqueda]=useState(''),[seleccion,setSeleccion]=useState(''),[archivo,setArchivo]=useState(''),[rad,setRad]=useState(''),[categoria,setCategoria]=useState<string>(''),[cuerpo,setCuerpo]=useState('[ANTECEDENTES VERIFICADOS]\n\n[OBJETO DE LA COMUNICACIÓN]\n\n[CONTENIDO SUJETO A REVISIÓN]'),[tipo,setTipo]=useState('Oficio'),[asunto,setAsunto]=useState(''),[destino,setDestino]=useState('');
 useEffect(()=>{try{const guardado=localStorage.getItem(STORAGE_KEY);if(guardado)setDatos(datosSchema.parse(JSON.parse(guardado)));}catch{setAviso('No se pudieron leer los datos guardados. Se muestra la demostración; el almacenamiento anterior no se ha sobrescrito.');}setListo(true);},[]);
 function guardar(nuevos:Datos){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(nuevos));setDatos(nuevos);setAviso('Guardado en este navegador.');}catch{setAviso('No se pudo guardar. Comprueba que el navegador permita almacenamiento local.');}}
 function crear(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const r=normalizarRadicado(campo(f,'radicado'));if(datos.expedientes.some(x=>normalizarRadicado(x.radicado)===r)){setAviso('Ese radicado ya existe.');return;}guardar({...datos,expedientes:[...datos.expedientes,{id:crypto.randomUUID(),radicado:r,asunto:campo(f,'asunto'),partes:campo(f,'partes'),estado:campo(f,'estado') as Estado,actuaciones:[]}]});e.currentTarget.reset();}
 const expediente=datos.expedientes.find(x=>x.id===seleccion);
 function actuacion(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!expediente)return;const f=new FormData(e.currentTarget);guardar({...datos,expedientes:datos.expedientes.map(x=>x.id===seleccion?{...x,actuaciones:[...x.actuaciones,{id:crypto.randomUUID(),fecha:campo(f,'fecha'),tipo:campo(f,'tipo'),descripcion:campo(f,'descripcion')}].sort((a,b)=>a.fecha.localeCompare(b.fecha))}:x)});e.currentTarget.reset();}
 function registrar(){if(!archivo)return;guardar({...datos,documentos:[...datos.documentos,{id:crypto.randomUUID(),nombre:archivo,radicado:'',categoria:categoria||'Sin clasificar',fecha:new Date().toISOString(),estado:'Pendiente de revisión'}]});setArchivo('');}
 const texto=`INSPECCIÓN RURAL DE CONVIVENCIA Y PAZ PANTANO DE VARGAS\nPAIPA – BOYACÁ\n\n${tipo.toUpperCase()} · PROYECTO SIN FIRMA\nRadicado: ${rad||'[POR DEFINIR]'}\nDestinatario o partes: ${destino||'[POR DEFINIR]'}\nAsunto: ${asunto||'[POR DEFINIR]'}\n\n${cuerpo}\n\nBORRADOR SUJETO A REVISIÓN. SIN FIRMA.`;
 function descargar(){const url=URL.createObjectURL(new Blob([texto],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='proyecto_'+(rad||'sin_radicado').replace(/[^a-z0-9-]/gi,'_')+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <><header><small>INSPECCIÓN RURAL DE CONVIVENCIA Y PAZ PANTANO DE VARGAS</small><h1>Gestión Jurídica</h1></header><main className="shell"><p className="warning">Demostración con datos ficticios. Los registros se guardan únicamente en este navegador. No usar documentos institucionales reales.</p><nav className="tabs" aria-label="Secciones">{tabs.map(t=><button key={t} className={tab===t?'active':''} aria-pressed={tab===t} onClick={()=>{setTab(t);setAviso('');}}>{t}</button>)}</nav><p role="status">{aviso}</p>{!listo?<p>Cargando demostración…</p>:<>
 {tab==='Inicio'&&<><div className="grid">{[['Expedientes',datos.expedientes.length],['Documentos pendientes',datos.documentos.filter(d=>d.estado==='Pendiente de revisión').length],['Audiencias',datos.audiencias.length]].map(([n,v])=><div className="card stat" key={n}><strong>{v}</strong><span>{n}</span></div>)}</div><section className="card"><h2>Archivo inteligente · Demostración</h2><p>Registra nombres de archivos ficticios, revisa la categoría sugerida y confirma el expediente antes de clasificar.</p><button onClick={()=>setTab('Archivo documental')}>Abrir bandeja documental</button><p className="hint">La clasificación usa el nombre del archivo; no lee su contenido. Google Drive, firma, PDF, grabación y sincronización están pendientes.</p></section></>}
 {tab==='Expedientes'&&<><section className="card"><h2>Expedientes</h2><label htmlFor="buscar">Buscar por radicado, asunto o partes</label><input id="buscar" value={busqueda} onChange={e=>setBusqueda(e.target.value)}/>{datos.expedientes.filter(x=>[x.radicado,x.asunto,x.partes].join(' ').toLocaleLowerCase('es').includes(busqueda.toLocaleLowerCase('es'))).map(x=><div className="line" key={x.id}><div className="row"><div><b>{x.radicado}</b><p>{x.asunto} · {x.partes}</p><span className="tag">{x.estado}</span></div><button className="secondary" onClick={()=>setSeleccion(x.id)}>Ver expediente {x.radicado}</button></div></div>)}</section><section className="card"><h2>Nuevo expediente ficticio</h2><form onSubmit={crear}><label>Radicado<input name="radicado" required maxLength={60}/></label><label>Asunto<input name="asunto" required maxLength={140}/></label><label>Partes ficticias<input name="partes" maxLength={140}/></label><label>Estado<select name="estado"><option>En trámite</option><option>Pendiente de audiencia</option><option>Archivado</option></select></label><button>Guardar expediente</button></form></section>{expediente&&<section className="card"><h2>Expediente {expediente.radicado}</h2><h3>Actuaciones</h3>{expediente.actuaciones.length?expediente.actuaciones.map(a=><p key={a.id}>{a.fecha} · {a.tipo}: {a.descripcion}</p>):<p>Sin actuaciones.</p>}<form onSubmit={actuacion}><label>Fecha<input name="fecha" type="date" required/></label><label>Tipo<select name="tipo"><option>Registro</option><option>Auto</option><option>Audiencia</option><option>Prueba</option><option>Notificación</option></select></label><label>Descripción ficticia<textarea name="descripcion" required maxLength={1000}/></label><button>Agregar actuación</button></form><h3>Carpetas documentales</h3>{categorias.map(c=><div className="folder" key={c}>{c} ({datos.documentos.filter(d=>d.radicado===expediente.radicado&&d.categoria===c&&d.estado==='Clasificado').length})</div>)}</section>}</>}
 {tab==='Archivo documental'&&<><section className="card"><h2>Bandeja documental</h2><p>Solo se registra el nombre ficticio. El archivo no se lee ni se sube.</p><label>Seleccionar archivo ficticio<input type="file" onChange={e=>{const n=e.target.files?.[0]?.name||'';setArchivo(n);setCategoria(sugerirCategoria(n)||'');e.target.value='';}}/></label>{archivo&&<><p>Archivo: {archivo}</p><p>Categoría sugerida: {categoria||'Sin clasificar'}</p><p>Radicados candidatos: {coincidenciasRadicado(archivo,datos.expedientes.map(x=>x.radicado)).join(', ')||'Ninguno'}. Requiere revisión humana.</p><button onClick={registrar}>Registrar pendiente de revisión</button></>}</section><section className="card"><h2>Índice local</h2>{!datos.documentos.length&&<p>No hay documentos registrados.</p>}{datos.documentos.map(d=><article className="line" key={d.id}><b>{d.nombre}</b><p>{d.categoria} · {d.radicado||'Sin expediente'} · {d.estado}</p>{d.estado==='Pendiente de revisión'&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const r=campo(f,'radicado'),c=campo(f,'categoria');if(!datos.expedientes.some(x=>x.radicado===r)||!categorias.includes(c as typeof categorias[number]))return;guardar({...datos,documentos:datos.documentos.map(x=>x.id===d.id?{...x,radicado:r,categoria:c,estado:'Clasificado'}:x)});}}><label>Expediente confirmado<select name="radicado" required defaultValue=""><option value="" disabled>Seleccionar expediente</option>{datos.expedientes.map(x=><option key={x.id}>{x.radicado}</option>)}</select></label><label>Categoría confirmada<select name="categoria" defaultValue={categorias.includes(d.categoria as typeof categorias[number])?d.categoria:''} required><option value="" disabled>Seleccionar categoría</option>{categorias.map(c=><option key={c}>{c}</option>)}</select></label><button>Confirmar clasificación</button></form>}</article>)}</section></>}
 {tab==='Plantillas'&&<section className="card"><h2>Plantillas de demostración</h2><p>Texto editable sujeto a revisión. No se generan documentos oficiales ni firmas.</p><label>Tipo<select value={tipo} onChange={e=>setTipo(e.target.value)}><option>Oficio</option><option>Auto de trámite</option></select></label><label>Radicado<input value={rad} onChange={e=>setRad(e.target.value)}/></label><label>Destinatario o partes<input value={destino} onChange={e=>setDestino(e.target.value)}/></label><label>Asunto<input value={asunto} onChange={e=>setAsunto(e.target.value)}/></label><label>Contenido editable<textarea value={cuerpo} onChange={e=>setCuerpo(e.target.value)}/></label><h3>Vista previa</h3><pre className="preview">{texto}</pre><button onClick={descargar}>Descargar borrador TXT</button></section>}
 {tab==='Agenda'&&<section className="card"><h2>Agenda ficticia</h2>{[...datos.audiencias].sort((a,b)=>a.fecha.localeCompare(b.fecha)).map(a=><div className="line" key={a.id}><b>{a.fecha.replace('T',' · ')}</b><p>{a.asunto} · {a.radicado} · {a.modalidad}</p></div>)}{!datos.audiencias.length&&<p>Sin audiencias.</p>}<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);guardar({...datos,audiencias:[...datos.audiencias,{id:crypto.randomUUID(),radicado:campo(f,'radicado'),fecha:campo(f,'fecha'),asunto:campo(f,'asunto'),modalidad:campo(f,'modalidad') as Audiencia['modalidad']}]});e.currentTarget.reset();}}><label>Fecha y hora local<input name="fecha" type="datetime-local" required/></label><label>Asunto de audiencia<input name="asunto" required maxLength={140}/></label><label>Expediente<select name="radicado" required>{datos.expedientes.map(x=><option key={x.id}>{x.radicado}</option>)}</select></label><label>Modalidad<select name="modalidad"><option>Presencial</option><option>Google Meet</option><option>Inspección ocular</option></select></label><p className="hint">Registrar Google Meet no crea una reunión ni conecta una cuenta.</p><button>Guardar audiencia</button></form></section>}
 {tab==='Dispositivos'&&<section className="card"><h2>Dispositivos · Pendiente</h2><p>La vinculación QR y la revocación remota requieren un backend con autenticación. Esta demostración no vincula equipos ni sincroniza datos.</p></section>}
 </>}</main></>;
}
